# Parameters for data preprocessing
data_preprocessing:
  imputation_strategy: "mean"

# Parameters for feature engineering
feature_engineering:
  polynomial_degree: 2

# Parameters for model training
model_training:
  test_size: 0.2
  random_state: 42
  models:
    linear_regression:
      fit_intercept: true
    random_forest:
      n_estimators: 100
      max_depth: null
      min_samples_split: 2
      min_samples_leaf: 1
    gradient_boosting:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 3
    neural_network:
      hidden_layer_sizes: [50, 50]
      max_iter: 1000
    svr:
      kernel: "linear"
      C: 1.0
      epsilon: 0.1
    xgboost:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 3

# Parameters for hyperparameter tuning
hyperparameter_tuning:
  cv: 5
  scoring: "neg_mean_absolute_error"
