# Parameters for 01_data_ingestion

data_ingestion:
  sa_lower_bound: 1.5                               # Lower bound for surface roughness
  sa_upper_bound: 2.5                               # Upper bound for surface roughness
  cell_viability_threshold: 90                      # Threshold for cell viability to determine pass/fail
  outlier_capping_method: "quantiles"               # Method for capping outliers
  outlier_tail: "both"                              # Tail(s) to apply the outlier capping
  outlier_fold: 0.05                                # Fold for Winsorizing
  log_transform_variable: "cell_viability_percent"  # Variable to apply log transformation

# Parameters for 02_data_validation

data_validation:
  knn_n_neighbors: 5                                # Number of neighbors for KNN imputation
  sa_lower_bound: 1.5                               # Lower bound for surface roughness
  sa_upper_bound: 2.5                               # Upper bound for surface roughness
  test_size: 0.2                                    # Test size for splitting
  random_state: 42                                  # Random state for reproducibility

# Parameters for 03_data_transformation

data_transformation:
  test_size: 0.2                                    # Test size for train-test split
  random_state: 42                                  # Random state for reproducibility
  polynomial_features_degree: 2                     # Degree for polynomial features
  scaling_method: "robust"                          # Scaling method (e.g., robust, standard)
  lasso_max_iter: 10000                             # Maximum iterations for Lasso regression
  knn_n_neighbors: 5                                # Number of neighbors for KNN imputation
