# Schema for the Sandblasting-Condition dataset

COLUMNS:
  Angle of Sandblasting: int64
  Pressure of Sandblasting (bar): int64
  Temperture of Acid Etching: int64
  Time of Acid Etching (min): int64
  Voltage of Anodizing (v): int64
  Time of  Anodizing (min): int64

TARGET_COLUMNS:
  (Sa) Average of Surface roughness (micrometer): float64
  Cell Viability (%): int64
  Result (1=Passed, 0=Failed): int64
