# Schema for the Sandblasting-Condition dataset

COLUMNS:
  angle_sandblasting: int64
  pressure_sandblasting_bar: int64
  temperature_acid_etching: int64
  time_acid_etching_min: int64
  voltage_anodizing_v: int64
  time_anodizing_min: int64

TARGET_COLUMNS:
  sa_surface_roughness_micrometer: float64
  cell_viability_percent: int64
  Result_Passed_1_Failed_0: int64
