artifacts_root: artifacts

# root directory for data ingestion artifacts
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/farshidhesami/Branching-tutorial/raw/master/Sandblasting-Condition.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

# root directory for data validation artifacts
data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Sandblasting-Condition.csv
  STATUS_FILE: artifacts/data_validation/status.txt

# root directory for data transformation artifacts
data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/Sandblasting-Condition.csv
  transformed_train_path: artifacts/data_transformation/train.csv
  transformed_test_path: artifacts/data_transformation/test.csv

# root directory for model trainer artifacts
model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
  poly_features_path: artifacts/model_trainer/models/poly_features.joblib  # Correct path
  model_path: artifacts/model_trainer/models
  sa_model_name: 'gradient_boosting'  # Best model for Surface Roughness
  cv_model_name: 'gradient_boosting'  # Best model for Cell Viability

# root directory for model evaluation artifacts
model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/models
  metric_file_name: artifacts/model_evaluation/metrics.json
  target_column: 'Result (1=Passed, 0=Failed)'
