artifacts_root: artifacts

# Root directory for data ingestion artifacts
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/farshidhesami/Branching-tutorial/raw/master/Sandblasting-Condition.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  columns_to_convert:
    - "pressure_sandblasting_bar"
    - "temperature_acid_etching"
    - "time_acid_etching_min"
    - "voltage_anodizing_v"
    - "time_anodizing_min"
    - "sa_surface_roughness_micrometer"
    - "cell_viability_percent"

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Sandblasting-Condition.csv
  STATUS_FILE: artifacts/data_validation/validation_status.txt
  knn_n_neighbors: 5
  sa_lower_bound: 1.5
  sa_upper_bound: 2.5
  feature_columns:
    - "angle_sandblasting"
    - "pressure_sandblasting_bar"
    - "temperature_acid_etching"
    - "time_acid_etching_min"
    - "voltage_anodizing_v"
    - "time_anodizing_min"
  target_column_sa: "sa_surface_roughness_micrometer"
  target_column_cv: "cell_viability_percent"

